#!/usr/bin/env python3

import sys, time, argparse, subprocess, os.path

Description = """
br-index integration test script.


やること

- datasetディレクトリの全ファイルについてイテレーションする
以下は一つのテキストについて

- パターンに確率1/20ぐらいで変異を起こしたファイルを作ってtest-tmpに格納する
- test-tmpにin-memoryなビルドとPFPなビルドを行った(bl=64で)インデックスファイルを格納
- それぞれをbl=0、bl=64の2パターンでロードする

→ビルドは2パターンだが、その後のテストは合計4パターン

ただ、各インデックスファイルに対するテストは同じ内容になるので、ここからをC++実行ファイルで作成する




"""

# absolute path of auxiliary executables
dirname = os.path.dirname(os.path.abspath(__file__))
bigbwt_exe      =  os.path.join(dirname, "pfpbuilder", "bigbwt")
build_exe       =  os.path.join(dirname, "pfpbuild")
shasum_exe      =  "sha256sum"

EXTIDX = ".bri"